// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relicarioApi.Data;

namespace relicarioApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211005023143_criacao database")]
    partial class criacaodatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("relicarioApi.Models.Artista", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoLonga")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("relicarioApi.Models.CategoriaGaleria", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("CategoriaPai")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GALERIA_CATEGORIA");
                });

            modelBuilder.Entity("relicarioApi.Models.CategoriaLoja", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("BarraSuperior")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("CodigoPai")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LOJA_CATEGORIA");
                });

            modelBuilder.Entity("relicarioApi.Models.CreditCard", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Bandeira")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleria", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("ArtistaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("CategoriaGaleriaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoLonga")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("CategoriaGaleriaId");

                    b.ToTable("GALERIA_PRODUTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleriaFoto", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(4000)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ProdutoGaleriaId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("ProdutoGategoriaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoGaleriaId");

                    b.ToTable("GALERIA_PRODUTO_FOTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLoja", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("CategoriaLojaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoLonga")
                        .HasColumnType("text");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Peso")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoOriginal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoPromocional")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaLojaId");

                    b.ToTable("LOJA_PRODUTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaAtributo", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProdutoLojaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoLojaId");

                    b.ToTable("LOJA_PRODUTO_ATRIBUTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaFoto", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(4000)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ProdutoLojaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoLojaId");

                    b.ToTable("LOJA_PRODUTO_FOTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaRelacionado", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ProdutoPrincipalId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("ProdutoRelacionadoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoPrincipalId");

                    b.HasIndex("ProdutoRelacionadoId");

                    b.ToTable("LOJA_PRODUTO_RELACIONADO");
                });

            modelBuilder.Entity("relicarioApi.Models.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("relicarioApi.Models.UserAdress", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("NomeDestinatario")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USUARIO_ENDERECO");
                });

            modelBuilder.Entity("relicarioApi.Models.CreditCard", b =>
                {
                    b.HasOne("relicarioApi.Models.User", null)
                        .WithMany("Cards")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleria", b =>
                {
                    b.HasOne("relicarioApi.Models.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relicarioApi.Models.CategoriaGaleria", "CategoriaGaleria")
                        .WithMany()
                        .HasForeignKey("CategoriaGaleriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("CategoriaGaleria");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleriaFoto", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoGaleria", null)
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoGaleriaId");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLoja", b =>
                {
                    b.HasOne("relicarioApi.Models.CategoriaLoja", "CategoriaLoja")
                        .WithMany()
                        .HasForeignKey("CategoriaLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaLoja");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaAtributo", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoLoja", "ProdutoLoja")
                        .WithMany("ProdutoLojaAtributos")
                        .HasForeignKey("ProdutoLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoLoja");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaFoto", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoLoja", null)
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaRelacionado", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoLoja", "ProdutoPrincipal")
                        .WithMany("ProdutosRelacionados")
                        .HasForeignKey("ProdutoPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relicarioApi.Models.ProdutoLoja", "ProdutoRelacionado")
                        .WithMany()
                        .HasForeignKey("ProdutoRelacionadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoPrincipal");

                    b.Navigation("ProdutoRelacionado");
                });

            modelBuilder.Entity("relicarioApi.Models.UserAdress", b =>
                {
                    b.HasOne("relicarioApi.Models.User", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleria", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLoja", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("ProdutoLojaAtributos");

                    b.Navigation("ProdutosRelacionados");
                });

            modelBuilder.Entity("relicarioApi.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
