// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relicarioApi.Data;

namespace relicarioApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211025223650_Add parameters")]
    partial class Addparameters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("relicarioApi.Models.Artista", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoLonga")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("relicarioApi.Models.CategoriaGaleria", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("CategoriaPai")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("GALERIA_CATEGORIA");
                });

            modelBuilder.Entity("relicarioApi.Models.CategoriaLoja", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("BarraSuperior")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("CodigoPai")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("LOJA_CATEGORIA");
                });

            modelBuilder.Entity("relicarioApi.Models.Numeros", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("relicarioApi.Models.Parameters", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Param")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Param")
                        .IsUnique();

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleria", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("ArtistaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("CategoriaGaleriaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoLonga")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(767)");

                    b.Property<byte[]>("ProdutoLojaId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("CategoriaGaleriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("GALERIA_PRODUTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleriaFoto", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ProdutoGaleriaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoGaleriaId");

                    b.ToTable("GALERIA_PRODUTO_FOTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLoja", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("CategoriaLojaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoLonga")
                        .HasColumnType("text");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Peso")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoOriginal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoPromocional")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaLojaId");

                    b.ToTable("LOJA_PRODUTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaAtributo", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProdutoLojaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoLojaId");

                    b.ToTable("LOJA_PRODUTO_ATRIBUTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaFoto", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ProdutoLojaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoLojaId");

                    b.ToTable("LOJA_PRODUTO_FOTO");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaRelacionado", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ProdutoPrincipalId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("ProdutoRelacionadoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoPrincipalId");

                    b.HasIndex("ProdutoRelacionadoId");

                    b.ToTable("LOJA_PRODUTO_RELACIONADO");
                });

            modelBuilder.Entity("relicarioApi.Models.Valores", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Icone")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleria", b =>
                {
                    b.HasOne("relicarioApi.Models.Artista", "Artista")
                        .WithMany("Produtos")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relicarioApi.Models.CategoriaGaleria", "CategoriaGaleria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaGaleriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("CategoriaGaleria");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleriaFoto", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoGaleria", null)
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoGaleriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLoja", b =>
                {
                    b.HasOne("relicarioApi.Models.CategoriaLoja", "CategoriaLoja")
                        .WithMany()
                        .HasForeignKey("CategoriaLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaLoja");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaAtributo", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoLoja", "ProdutoLoja")
                        .WithMany("ProdutoLojaAtributos")
                        .HasForeignKey("ProdutoLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoLoja");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaFoto", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoLoja", null)
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLojaRelacionado", b =>
                {
                    b.HasOne("relicarioApi.Models.ProdutoLoja", "ProdutoPrincipal")
                        .WithMany("ProdutosRelacionados")
                        .HasForeignKey("ProdutoPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relicarioApi.Models.ProdutoLoja", "ProdutoRelacionado")
                        .WithMany()
                        .HasForeignKey("ProdutoRelacionadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoPrincipal");

                    b.Navigation("ProdutoRelacionado");
                });

            modelBuilder.Entity("relicarioApi.Models.Artista", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("relicarioApi.Models.CategoriaGaleria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoGaleria", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("relicarioApi.Models.ProdutoLoja", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("ProdutoLojaAtributos");

                    b.Navigation("ProdutosRelacionados");
                });
#pragma warning restore 612, 618
        }
    }
}
